const API_URL = {
    USER_DATA: "/api/auth/user/",
    STRIPE_KEY: "/api/stripe/pk/",
    USER_PLAN_DETAILS: "/api/user_plans/",
    SUBSCRIBE: "/api/users/subscribe/",
    BUY_CREDITS: "/api/listing_credits/buy/",
    CUSTOMER_DETAILS: "/api/users/customer/",
    LOGIN_USER: "/api/auth/login/",
    LOGIN_GOOGLE: "/api/auth/google/",
    LOGIN_FACEBOOK: "/api/auth/facebook",
    REGISTER_USER: "/api/auth/register/",
    PASSWORD_RESET: "/api/auth/password/reset/",
    PASSWORD_RESET_CONFIRM: "/api/auth/password/reset/confirm/",
    VERIFY_EMAIL: "/api/auth/verify-email/",
    LOGOUT_USER: "/api/auth/logout/",
    UPDATE_USER_PROFILE: "/api/users/profile/update/",
    USER_LOCATIONS: "/api/countries/",
    DOCUMENTS: "/api/documents/",
    RACES: "/api/races/",
    RACE_DETAILS: "/api/races/",
    ADD_RACE: "/api/races/add/",
    IMPORT_RACE: "/api/races/import/",
    DELETE_RACE: "/api/races/",
    MARKETER_REPORT: "/api/races/",
    MARKETER_LIST_RACE: "/api/races/",
    RACE_FORM_DATA: "/api/races/form_data/",
    SPONSORS: "/api/races/",
    SPONSORS_BROKEN_LINK: "/api/sponsor/",
    VENDOR_OFFERS: "/api/offers/",
    CLAIM_VENDOR_OFFER: "/api/offers/",
};

export default API_URL;
